### PR TITLE
Mention the annotation config when misconfigured

### LINKED ISSUE #894: Improve "missing @MicronautTest" annotation error message
### Expected Behavior

When using @MicronautTest as meta annotation it should work
```java
@Inherited
@Retention(RUNTIME)
@MicronautTest(environments = "integration")
public @interface DatabaseTest {}
```

### Actual Behaviour

```
org.junit.jupiter.engine.execution.ConditionEvaluationException: Failed to evaluate condition [io.micronaut.test.extensions.junit5.MicronautJunit5Extension]: @MicronautTest used on test but no bean definition for the test present. This error indicates a misconfigured build or IDE. Please add the 'micronaut-inject-java' annotation processor to your test processor path (for Java this is the testAnnotationProcessor scope, for Kotlin kaptTest and for Groovy testCompile). See the documentation for reference: https://micronaut-projects.github.io/micronaut-test/latest/guide/
```

### Steps To Reproduce

1. `git clone https://github.com/nbrugger-tgm/micronaut-reproductions`
2. `cd micronaut-reproductions`
3. `./gradlew :894:test`

### Additional Info
When using the @MicronautTest directly on the test it works

### Environment Information

- JDK: 17, 20
- OS: Linux/Ubuntu

### Example Application

_No response_

### Version

4.10.1

### PR DESCRIPTION
**Pull request by timyates**
Closes #894

### CODE REVIEW

File: test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java [hunk 1]
```diff
@@ -74,7 +74,12 @@ public abstract class AbstractMicronautExtension<C> implements TestExecutionList
...
     public static final String TEST_TRANSACTION_MODE = "micronaut.test.transaction-mode";
     public static final String DISABLED_MESSAGE = "Test is not bean. Either the test does not satisfy requirements defined by @Requires or annotation processing is not enabled. If the latter ensure annotation processing is enabled in your IDE.";
-    public static final String MISCONFIGURED_MESSAGE = "@MicronautTest used on test but no bean definition for the test present. This error indicates a misconfigured build or IDE. Please add the 'micronaut-inject-java' annotation processor to your test processor path (for Java this is the testAnnotationProcessor scope, for Kotlin kaptTest and for Groovy testCompile). See the documentation for reference: https://micronaut-projects.github.io/micronaut-test/latest/guide/";
+    public static final String MISCONFIGURED_MESSAGE = """
+        @MicronautTest used on test but no bean definition for the test present. \
+        This error indicates a misconfigured build or IDE. \
+        Please check 'micronaut.processing.group' or 'micronaut.processing.annotations' in your build. \
```
Comment (sdelamo) [inline test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java:80]: what is meant by `Please check 'micronaut.processing.group' or 'micronaut.processing.annotations' in your build.`?

Comment (timyates) [reply test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java:80]: In [the original issue](https://github.com/micronaut-projects/micronaut-test/issues/894), an issue was that the 

```
micronaut {
  processing {
    annotations('xxxx')
 }
}
```

Was incorrect, this is what I meant my `'micronaut.processing.annotations' in your build`

In Maven builds, this is a property `micronaut.processing.group`

Comment (sdelamo) [reply test-core/src/main/java/io/micronaut/test/extensions/AbstractMicronautExtension.java:80]: but that it is not required. is it? I mean you don't even have to use our build plugins to use Micronaut Test. am I missing something?
