### PR TITLE
Split @Sql scripts into executable statements

### LINKED ISSUE #1091: @Sql annotation needs to do statement splitting
### Expected Behavior

SQL scripts that contain multiple statements separated by semi-colon should work on all databases.

### Actual Behaviour

On Oracle you get an error like:

```
java.sql.SQLException: ORA-03048: SQL reserved word ';' is not syntactically valid following 'DELETE FROM MYTABLE'
```

This happens because JDBC by spec only accepts one SQL statement per call, although you can use `addBatch` to add more than one. Some JDBC drivers conveniently split multi-statement strings for you, but they aren't required to do so and Oracle's driver doesn't. So Micronaut needs to do it. This is a general problem and from looking around the internet it seems splitting SQL scripts into statements probably has re-usable implementations elsewhere.

### Workaround

Wrap the script in a transaction like this:

```
BEGIN
stmt1;
stmt2;
COMMIT;
END;
```

### Steps To Reproduce

1. Create a `@MicronautTest` and use something like `@Sql(scripts = "classpath:clear-data.sql", phase = Sql.Phase.BEFORE_ALL)`
2. Put multiple statements in `clear-data.sql` separated by semi-colons on separate lines.
3. Run the test.

### Environment Information

Oracle JDBC driver `com.oracle.database.jdbc:ojdbc11-production:23.4.0.24.05`

### Example Application

_No response_

### Version

4.5.0

### PR DESCRIPTION
**Pull request by graemerocher**
## Summary
- split `@Sql` scripts into executable statements for JDBC and R2DBC handlers
- preserve semicolons inside quoted strings and SQL comments, while keeping PL/SQL blocks intact
- add focused tests for the statement splitter and both SQL handlers
- Fixes https://github.com/micronaut-projects/micronaut-test/issues/1091

## Verification
- `./gradlew :micronaut-test-core:test --tests 'io.micronaut.test.support.sql.DataSourceSqlHandlerTest' --tests 'io.micronaut.test.support.sql.ConnectionFactoryHandlerTest'`

### CODE REVIEW

**Comment by graemerocher** [comment]
@copilot apply changes based on the comments in [this thread](https://github.com/micronaut-projects/micronaut-test/pull/1435#pullrequestreview-4104452862)

File: test-core/src/test/java/io/micronaut/test/support/sql/ConnectionFactoryHandlerTest.java [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+import org.junit.jupiter.api.Test;
+import reactor.core.publisher.Mono;
+
+import java.lang.reflect.Proxy;
+import java.util.ArrayList;
+import java.util.List;
+
+import static org.junit.jupiter.api.Assertions.assertEquals;
+
+class ConnectionFactoryHandlerTest {
```
Comment (mikehearn) [inline test-core/src/test/java/io/micronaut/test/support/sql/ConnectionFactoryHandlerTest.java]: This test is low value and could be removed. What matters here is the splitting logic, not the part that feeds it into jdbc.

File: test-core/src/test/java/io/micronaut/test/support/sql/DataSourceSqlHandlerTest.java [hunk 2]
```diff
@@ -0,0 +1,140 @@
...
+import java.util.List;
+
+import static org.junit.jupiter.api.Assertions.assertEquals;
+
+class DataSourceSqlHandlerTest {
+
+    private final DataSourceSqlHandler handler = new DataSourceSqlHandler();
+
+    @Test
+    void executesMultiStatementScriptsOneStatementAtATime() {
```
Comment (mikehearn) [inline test-core/src/test/java/io/micronaut/test/support/sql/DataSourceSqlHandlerTest.java]: This specific test method is low value and could be removed. Focus the testing on the SQL splitter class, not the wiring into JDBC.

**Review by mikehearn — CHANGES_REQUESTED** [review]

**Comment by graemerocher** [comment]
@copilot review

**Review by mikehearn — APPROVED** [review]

**Review by sdelamo — APPROVED** [review]
